### ISSUE TITLE
Clashes with Ionic (cordova-plugin-ionic-webview)

### ISSUE THREAD

**Issue by Edmu** [usabilla/usabilla-u4a-cordova#19]
This plugin clashes with Ionic (to be more specific 'cordova-plugin-ionic-webview' plugin part) which is I guess most popular cordova based framework.

This plugin implementation messes with activity and some code which is set via 'cordova-plugin-ionic-webview' is missing.

window.WEBVIEW_SERVER_URL is missing so 'window.Ionic.WebView.convertFileSrc' starts producing bad results and I guess there should be more faults due to 'hijacking' activity as 'cordova-plugin-ionic-webview' does same and sets some constant and methods there.

**Comment by torkvell** [comment]
Hi @Edmu,

Thank you for reaching out on this. Could you please elaborate on which specific action that is causing this crash? We have to make use of the activity to be able to display the feedback forms. You should be able to set window.WEBVIEW_SERVER_URL yourself in the source code as the whole SDK is opened sourced.

**Comment by Edmu** [comment]
Hello @torkvell 

I have never said the app is crashing - it's worse (in some sense) - it works but some of the things starts to break window.Ionic.WebView.convertFileSrc method is failing which causes local images fails to be loaded. I do not want to monkey patch window.WEBVIEW_SERVER_URL as I'm not sure I will cover whole 'cordova-plugin-ionic-webview' plugin functionality so If I miss something the app fill fail in some places and it will hard to find those bugs. 

As this plugin uses this way of implementation (overriding MainActivity) 

=>

var newManifest = androidManifest.replace('android:name="MainActivity"', 'android:name="com.usabilla.MainActivity"');

We will not be using Usabilla to collect feedback on app that is written with Ionic. As I do not expect this to be fixed I guess I'm justing creating this issue so ppl who uses Ionic can find this issue up-front and decide if they want to use this plugin.

**Comment by torkvell** [comment]
Hi @Edmu,

Great to hear it's working and I'm sorry to hear you can't make it work for Ionic. Unfortunately, this is not something we can prioritize from our end for now. However, thank you for reporting on this so we can make notes on the issue you're experiencing. 

If there is anything else in regards to the SDK then please let us know.
