### ISSUE TITLE
Reference error: Usabilla is undefined

### ISSUE THREAD

**Issue by GMuthuraja** [usabilla/usabilla-u4a-cordova#20]
I have installed this plugin in Cordova/Ionic application and then try to initialize the Usabilla with APP ID as given below. But it throws error as Usabilla is undefined in my browser console

> declare var Usabilla: any;
...
...
export class AppComponent {
constructor(){
Usabilla.initialize(
      function() {
       cconsole.log('success');
      },
      function () {
       console.log('error');
      },
      "xxxxx-xdxx-xx9-8x-xxx", //Usabilla App ID 
       "XXXX" // Custom Variable
      );
 }
}

**Comment by torkvell** [comment]
Hi @GMuthuraja ,

Thank you for reaching out on this. As already shared with you through email I'll do some testing on this and come back to you once I have any updates. Thank you for your patience on this and please let me know if you have any news to this in the meantime.

**Comment by torkvell** [comment]
Hi @GMuthuraja ,

Thank you for your patience on this. I've just done some testing with the sample app we have included in this repository. I get no reference errors thrown when I run it through my browser. I've also tested the sample app with an appId and some custom variables. I can trigger a campaign and the feedback form. I'm also able to send the feedback successfully to our back-end.

Please have a look at our example code on how to go about initializing the SDK: https://github.com/usabilla/usabilla-u4a-cordova/blob/master/UsabillaSampleApp/www/js/index.js
