### ISSUE TITLE
Backbutton won't close the app on Android in Ionic

### ISSUE THREAD

**Issue by rvdleun** [usabilla/usabilla-u4a-cordova#7]
I'm currently in the process of implementing the Usabilla SDK into our Ionic application to receive feedback from our user base. Overall, the implementation went pretty smoothly and the forms were showing up quickly.

However, we are currently running into an issue where the backbutton won't close the app on the root page. When removing the plugin, this behaviour is restored again. To test this further, I've also created a new project in Ionic and the same thing happened.

Curiously, when I created a new Cordova app, the app closed as expected, so this might possibly be something with the Ionic framework.

One thing that does stand out for both Cordova and Ionic is that when I deploy the app, it does not auto-start on my device, which normally happens if the plugin is not installed.

If there is any possible way to fix this, I would love to hear how. Thanks.

**Comment by kioli** [comment]
Hi @rvdleun and sorry for the delayed reply

We haven't done Ionic investigation so far and have therefore not experienced this misbehaviour of the framework.

We did experience though the fact that the Cordova app does not start itself automatically when launched via command line but needs a click on the icon.
We are not sure why this behaviour presents itself sine it's not undermining its correct behaviour once installed and launched as a user would do

**Comment by torkvell** [comment]
https://github.com/usabilla/usabilla-u4a-cordova/issues/19
